---
version: "2"
linters:
  enable:
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - revive
    - unconvert
  settings:
    errcheck:
      check-blank: true
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
