---
name: CI
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [main, devel]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main, devel]

permissions:
  contents: read
  pull-requests: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: ${{ github.repository_owner }}/dse
  PACKAGE_VERSION: 0.0.2
  package_name: CLib
  build_dir: null  # Disables package generation (code only repo).
  CCACHE_SECONDARY_STORAGE: ${{ secrets.CCACHE_SECONDARY_STORAGE }}

jobs:
  build:
    runs-on: [ubuntu-latest]
    needs: []
    strategy:
      matrix:
        package_arch:
          - linux-amd64
    container:
      image: ghcr.io/boschglobal/dse-gcc-builder:main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build package metadata
        id: package_meta
        uses: docker/metadata-action@v4
        with:
          images: dse/clib
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Get package version
        if: startsWith(github.ref, 'refs/tags/')
        id: package
        run: |
          echo "PACKAGE_VERSION=${{ fromJSON(steps.package_meta.outputs.json).labels['org.opencontainers.image.version'] }}" >> $GITHUB_ENV

      - name: Build
        env:
          PACKAGE_ARCH: ${{ matrix.package_arch }}
        run: |
          make

      - name: Test
        if: ${{ matrix.package_arch == 'linux-amd64' }}
        env:
          PACKAGE_ARCH: ${{ matrix.package_arch }}
        run: |
          make test_cmocka

  test_go:
    runs-on: [ubuntu-latest]
    needs: []
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          make test_go
