---
name: Docker

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    paths:
      - 'extra/docker/**'

permissions:
  contents: read
  pull-requests: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: ${{ github.repository_owner }}/dse

jobs:
  container:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        image:
          - clang-format
          - flatc-builder
          - gcc-builder
          - python-builder
          - testscript
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}-${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=main,enable=true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./extra/docker/${{ matrix.image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
