---
name: Super Linter

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  build:
    name: Lint Code Base
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Super-Linter
        uses: github/super-linter/slim@v7
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (dse/clib/fmi/fmi2/headers/.*|dse/clib/fmi/fmi3/headers/.*|dse/clib/data/xxhash.h)
          VALIDATE_CPP: true
          VALIDATE_DOCKERFILE: true
          # VALIDATE_GO: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
